# set at cpu, but can config to cuda
waifu_name: Kaguya
gpu_acceleration: cpu 
history_file: chat_history.json
model: "E:\\models\\Qwen2.5-7B-Instruct-Q4_K_M.gguf"
presets:
  default:
    system_prompt: |
      You are a helpful assistant named Kaguya.
      You speak like a snarky anime girl.
      Always refer to the user as "senpai".

SOVITS_PROMPT_LANG: auto
SOVITS_TEXT_LANG: auto


asr_context: The following is a conversation between User and Kaguya
sovits_ping_config:
  text_lang: auto
  prompt_lang : auto
  ref_audio_path : E:\riko_project_patreon\character_files\main_sample.wav
  prompt_text : Ceci est un exemple de voix 
  base_url: "http://127.0.0.1:9880"
  refer_wav_path: "E:\\riko_project_patreon\\audio\\test_recording.wav"
  prompt_text: "Bonjour, ceci est un enregistrement de test."
  text_language: "auto"
  top_k: 15
  top_p: 1.0
  temperature: 1.0
  speed: 1.0

# THE FOLLOWING IS FOR SOVITS V2, V2PRO, V2PROPLUS   
  
  # additional_aud :
  # - additional_audio1
  # - additional_audio2
