# set at cpu, but can config to cuda
waifu_name: riko
gpu_acceleration: cpu 
history_file: chat_history.json
model: "gpt-4.1-mini"
presets:
  default:
    system_prompt: |
      You are a helpful assistant named Riko.
      You speak like a snarky anime girl.
      Always refer to the user as "senpai".

asr_context: The following is a conversation between Rayen and Riko
sovits_ping_config:
  text_lang: fr
  prompt_lang : fr
  ref_audio_path : E:\riko_project_patreon\character_files\main_sample.wav
  prompt_text : Ceci est un exemple de voix 

# THE FOLLOWING IS FOR SOVITS V2, V2PRO, V2PROPLUS   
  
  # additional_aud :
  # - additional_audio1
  # - additional_audio2
